---
title: "Lab1RMD"
author: "Brandon Kim"
date: '2023-04-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r qqplot function}
qqcreate <- function(x) {
  normalized_vals <- sort(rnorm(length(x), mean = mean(x), sd = sd(x))) 
  # Create a sorted vector of random normally distributed values with the mean and sd of the inputted vector
  vector <- sort(x)
  df <- data.frame(vector, normalized_values)
  # since both vectors are sorted, having them put together in a dataframe will match the values from low to high.
  
  plt <- df %>%
    ggplot(aes(vector, normalized_values)) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    ggtitle("qqplot")
  #Create a scatterplot with a line y = x. 
  
  return(plt)
}
```

```{r readcsv}
df_oscars <- read_csv(here::here("Oscars-demographics-DFE.csv"))
head(df_oscars)
```

```{r}
df_oscars %>% 
  filter(award %in% c("Best Director", 
                       "Best Actor", 
                       "Best Actress", 
                       "Best Supporting Actor", 
                       "Best Supporting Actress")) %>%
  group_by(movie) %>%
  summarise(unique = nlevels(factor(award))) %>%
  filter(unique == max(unique))
```

```{r}
df_oscars %>%
  filter(award == "Best Actress") %>%
  mutate(first_name = sub(" .*", "", person)) %>%
  count(first_name) %>%
  filter(n == max(n))
```

```{r}
df_oscars %>% 
  mutate(birthplace = ifelse(birthplace=="New York City", "Ny", birthplace),
         region = sub(".*, ", "", birthplace)) %>%
  count(region) %>%
  filter(n == max(n))
```









